### ISSUE TITLE
Since el Capitan toolbelt no longer working

### ISSUE THREAD

**Issue by samjbmason** [heroku/toolbelt#138]
Since I upgraded to el Captian, Im having problems getting toolbelt to work, I use `rbenv` and `toolbelt` and have installed both using `homebrew`. Whenever I run heroku in my command line I get the message `rbenv: heroku: command not found`

Is this a known issue?

**Comment by ransombriggs** [comment]
It sounds like your PATH got messed up.  Could you echo out your path and make sure that it includes your homebrew bin path (it is most likely /usr/local/bin).  Fixing your PATH variable will depend on which shell you are currently using.

**Comment by samjbmason** [comment]
Im using ZSH here is my path as configured in my .zshrc file `export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"`

**Comment by ransombriggs** [comment]
Could you check ~/.rbenv/shims/ for a file for heroku?  From your output it looks like it might be trying to execute an rbenv shim instead of executing /usr/local/bin/heroku directly.

**Comment by samjbmason** [comment]
So when I run `ls ~/.rbenv/shims/` it shows a file called `heroku`. Should that not be there?

**Comment by ransombriggs** [comment]
At some point you (or a dependency) installed the gem heroku, and rbenv created a shim for that which no longer works.  If you do not need the heroku gem installed I would remove it because it is deprecated and it should pick up your homebrew installation if you remove it.

    -> % gem uninstall heroku
    Remove executables:
    	heroku

    in addition to the gem? [Yn]  y
    Removing heroku
    Successfully uninstalled heroku-3.42.21

**Comment by samjbmason** [comment]
Ah right, so this is something with rbenv as I use gemsets I fear this will take an age to figure out which project is installing the executable

**Comment by ransombriggs** [comment]
Ah, this is making more sense now, because whatever gemset you are currently using does not have the heroku gem installed, but the executable still exists.  Another option would be to put the homebrew directory before the shims one in your PATH (with the caveat that it may break something where you were depending on an executable in shims over one from homebrew).  The easiest way to do this would be to add the following after your rbenv init in your .zshrc, since the rbenv init is the way the shims get added to your PATH.

export PATH=/usr/local/bin:$PATH

**Comment by samjbmason** [comment]
Ah thats great thanks for that I will do some searching :)

**Comment by zeke** [comment]
This just bit me after an upgrade to OS X El Capitan. A fresh install using the package installer at toolbelt.heroku.com did the trick for me.
